#!/usr/bin/env bash
#
# Write an image made by backup-emmc.sh back onto the tablet's eMMC. Run from
# the live session, with the external disk holding the image attached.
#
# This is the most destructive operation in the repository: it overwrites the
# whole target device, partition table included. It exists as a script rather
# than a copy-paste dd line precisely so the target gets checked and confirmed
# instead of being whatever the shell history had in it.

# shellcheck source-path=SCRIPTDIR source=lib.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/lib.sh"

image=
target=
skip_checksum=no

usage() {
  cat <<EOF
Usage: sudo ${0##*/} --image FILE.img.zst --target /dev/mmcblkN [--skip-checksum]

  --image FILE       Image written by backup-emmc.sh (.zst, .xz, .gz or raw .img)
  --target DEV       Whole-disk device to overwrite (check with lsblk)
  --skip-checksum    Do not verify FILE against its .sha256 sidecar

Everything on DEV is destroyed and replaced by the contents of FILE.
EOF
}

while [ $# -gt 0 ]; do
  case $1 in
  --image)
    image=${2:?--image needs a path}
    shift 2
    ;;
  --target)
    target=${2:?--target needs a device}
    shift 2
    ;;
  --skip-checksum)
    skip_checksum=yes
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *) die "unknown argument: $1 (try --help)" ;;
  esac
done

[ -n "$image" ] && [ -n "$target" ] || {
  usage
  exit 2
}
[ "$(host_os)" = linux ] || die "run this on the tablet, from a Linux session"
[ "$(id -u)" -eq 0 ] || die "must run as root (writing a raw block device)"
[ -f "$image" ] || die "no such image: $image"
[ -b "$target" ] || die "not a block device: $target"

require_cmd lsblk dd blockdev awk

# ---------------------------------------------------------------------------
# Refuse the obviously wrong targets before anything else
# ---------------------------------------------------------------------------

# Writing to the device the image itself lives on destroys the image mid-restore.
image_src=$(df -P "$image" | awk 'NR == 2 { print $1 }')
case $image_src in
"$target"*) die "$image lives on $target. You would overwrite it while reading it." ;;
esac

# A whole-disk node, not a partition: restoring a full-disk image onto p1 would
# silently produce a corrupt device.
if [ -e "/sys/class/block/$(basename -- "$target")/partition" ]; then
  die "$target is a partition. Pass the whole-disk device (e.g. /dev/mmcblk0)."
fi

mounted=$(lsblk -nro MOUNTPOINT "$target" | grep -v '^$' || true)
if [ -n "$mounted" ]; then
  log "Still mounted from $target:"
  printf '%s\n' "$mounted" >&2
  die "unmount everything on $target first - restoring under a live mount corrupts both."
fi

# ---------------------------------------------------------------------------
# Pick the decompressor from the extension
# ---------------------------------------------------------------------------

case $image in
*.zst) require_cmd zstd; decompress=(zstd -dc) ;;
*.xz) require_cmd xz; decompress=(xz -dc) ;;
*.gz) require_cmd gzip; decompress=(gzip -dc) ;;
*.img) decompress=(cat) ;;
*) die "unrecognised image extension: $image (expected .img, .img.zst, .img.xz or .img.gz)" ;;
esac

# ---------------------------------------------------------------------------
# Verify the image before touching the target
# ---------------------------------------------------------------------------

sidecar=${image%.img.*}.sha256
[ -f "$sidecar" ] || sidecar=${image%.img}.sha256

if [ "$skip_checksum" = yes ]; then
  warn "checksum verification skipped at your request"
elif [ -f "$sidecar" ]; then
  log "Verifying $image against $sidecar (this reads the whole file)..."
  # Normalised for case: a sidecar regenerated by some other tool may be
  # uppercase, and that is not a mismatch.
  expected=$(awk '{ print tolower($1); exit }' "$sidecar")
  actual=$(sha256_of "$image")
  [ -n "$expected" ] || die "$sidecar is empty"
  [ "$actual" = "$expected" ] || die "checksum mismatch - the image is damaged.
  expected: $expected
  actual:   $actual"
  log "Checksum OK."
else
  # An unverifiable image restored over the only copy of the system is exactly
  # the situation a backup is supposed to prevent. Make the operator say so.
  warn "no .sha256 sidecar found next to $image"
  confirm_exact "UNVERIFIED" \
    "The image cannot be checked for damage. A corrupt image restores a corrupt system."
fi

# ---------------------------------------------------------------------------
# Describe the target and make the operator type it back
# ---------------------------------------------------------------------------

target_bytes=$(blockdev --getsize64 "$target")
log ""
log "Image:  $image ($(($(wc -c <"$image") / 1024 / 1024)) MiB compressed)"
log "Target: $target ($((target_bytes / 1024 / 1024 / 1024)) GiB) - contents below will be gone"
lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL "$target" >&2
log ""
confirm_exact "RESTORE $target" \
  "This overwrites all of $target, partition table included. There is no undo."

# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

log ""
log "Restoring. Do not unplug anything; an interrupted write leaves $target unbootable."

# No conv=noerror: a write error here means the restore did not happen, and the
# operator needs to know that rather than get a half-written device reported OK.
"${decompress[@]}" "$image" | dd of="$target" bs=4M status=progress conv=fsync ||
  die "restore failed - $target is now in an undefined state. Re-run before rebooting."

sync
blockdev --rereadpt "$target" 2>/dev/null || true

log ""
log "Done. Partition table now on $target:"
lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL "$target" >&2
log ""
log "Remove the USB devices and reboot."
